# Generated by Django 4.0.3 on 2022-04-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_remove_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
