# Generated by Django 2.2.12 on 2022-05-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("roll", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
            ],
        ),
    ]
